name: Build PHP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          echo "matrix={
            \"php-version\": [\"7.2.34\", \"7.3.33\", \"7.4.33\", \"8.0.30\", \"8.1.27\", \"8.2.17\"],
            \"include\": [
              {\"os\": \"ubuntu-latest\", \"target\": \"linux-64\"},
              {\"os\": \"ubuntu-latest\", \"target\": \"linux-aarch64\"},
              {\"os\": \"windows-latest\", \"target\": \"win-64\"},
              {\"os\": \"macos-latest\", \"target\": \"osx-64\"},
              {\"os\": \"macos-14-arm64\", \"target\": \"osx-arm64\"}
            ]
          }" >> $GITHUB_OUTPUT

  build:
    needs: prepare-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.prepare-matrix.outputs.matrix) }}

    steps:
    - uses: actions/checkout@v4
    
    # Install Rust and Rattler
    - uses: dtolnay/rust-toolchain@stable
    - run: cargo install rattler-build

    - name: Setup QEMU (for ARM builds)
      if: matrix.target == 'linux-aarch64'
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64

    - name: Generate rattler.yaml
      run: |
        mkdir -p recipe
        cat > recipe/rattler.yaml << EOF
        package:
          name: php
          version: ${{ matrix.php-version }}
        
        source:
          url: https://www.php.net/distributions/php-${{ matrix.php-version }}.tar.gz
        
        build:
          number: 0
        
        dependencies:
          build:
            - openssl-dev
            - libxml2-dev
            - zlib-dev
            - readline-dev  # [not win]
            - sqlite-dev
            - curl-dev
            - icu-dev
            - oniguruma-dev
            - re2c
            - bison
            - make
            - perl  # [not win]
          host:
            - openssl
            - libxml2
            - zlib
            - readline  # [not win]
            - sqlite
            - curl
            - icu
            - oniguruma
          run:
            - openssl
            - libxml2
            - zlib
            - readline  # [not win]
            - sqlite
            - curl
            - icu
            - oniguruma
        
        test:
          commands:
            - php --version
        EOF

    - name: Build PHP
      run: |
        rattler-build build recipe/rattler.yaml \
          --target-platform ${{ matrix.target }} \
          ${{ matrix.target == 'linux-aarch64' && '--no-test' || '' }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: php-${{ matrix.php-version }}-${{ matrix.target }}
        path: dist/${{ matrix.target }}/*.conda

    - name: Test PHP installation
      if: matrix.target != 'linux-aarch64'
      run: |
        rattler-build test recipe/rattler.yaml
