name: Build PHP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          echo "matrix={
            \"php-version\": [\"7.2.34\", \"7.3.33\", \"7.4.33\", \"8.0.30\", \"8.1.27\", \"8.2.17\"],
            \"include\": [
              {\"os\": \"ubuntu-latest\", \"target\": \"linux-64\"},
              {\"os\": \"ubuntu-latest\", \"target\": \"linux-aarch64\"},
              {\"os\": \"windows-latest\", \"target\": \"win-64\"},
              {\"os\": \"macos-latest\", \"target\": \"osx-64\"},
              {\"os\": \"macos-14-arm64\", \"target\": \"osx-arm64\"}
            ]
          }" >> $GITHUB_OUTPUT

  build:
    needs: prepare-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.prepare-matrix.outputs.matrix) }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup QEMU (for ARM builds)
      if: matrix.target == 'linux-aarch64'
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64

    - name: Create recipe directory
      run: mkdir -p recipe

    - name: Generate recipe.yaml
      run: |
        cat > recipe/recipe.yaml << EOF
        package:
          name: php
          version: ${{ matrix.php-version }}
        
        source:
          url: https://www.php.net/distributions/php-${{ matrix.php-version }}.tar.gz
        
        build:
          number: 0
        
        requirements:
          build:
            - {{ compiler('c') }}
            - {{ compiler('cxx') }}
            - autoconf
            - automake
            - libtool
            - pkg-config
            - re2c
            - bison
            - make
            - perl    # [not win]
          host:
            - openssl
            - libxml2
            - zlib
            - readline # [not win]
            - libsqlite
            - curl
            - icu
            - oniguruma
          run:
            - openssl
            - libxml2
            - zlib
            - readline # [not win]
            - libsqlite
            - curl
            - icu
            - oniguruma
        
        test:
          commands:
            - php --version
        EOF

    - name: Build PHP
      uses: prefix-dev/rattler-build-action@v0.2.21
      with:
        recipe-path: recipe/recipe.yaml
        artifact-name: php-${{ matrix.php-version }}-${{ matrix.target }}
        build-args: >-
          --target-platform ${{ matrix.target }}
          ${{ matrix.target == 'linux-aarch64' && ' --no-test' || '' }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: php-${{ matrix.php-version }}-${{ matrix.target }}
        path: dist/${{ matrix.target }}/*.tar.bz2

    - name: Test PHP installation (if not cross-compile)
      if: matrix.target != 'linux-aarch64'
      run: |
        php --version
