name: Build PHP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build PHP ${{ matrix.version }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60  # PHP builds can take longer
    strategy:
      fail-fast: false
      matrix:
        version: [7.2.34, 7.3.33, 7.4.33, 8.0.30, 8.1.27, 8.2.17]
        os: [ubuntu-latest, macos-13, macos-latest, windows-latest]
        rattler-build-version: [''] # default version

    steps:
      - uses: actions/checkout@v4
      
      - name: Create recipe
        shell: bash
        run: |
          mkdir -p recipe
          cat > recipe/recipe.yaml << 'EOF'
          package:
            name: php
            version: ${{ matrix.version }}
          
          source:
            url: https://www.php.net/distributions/php-${{ matrix.version }}.tar.gz
          
          build:
            script: |
              ./configure \
                --prefix=$PREFIX \
                --enable-mbstring \
                --with-openssl \
                --with-sqlite3 \
                --with-zlib \
                --with-curl
              make -j$CPU_COUNT
              make install
          
          requirements:
            build:
              - {{ compiler('c') }}
              - {{ compiler('cxx') }}
              - autoconf
              - automake
              - libtool
              - pkg-config
              - re2c
              - bison
              - make
              - perl    # [not win]
            host:
              - openssl
              - libxml2
              - zlib
              - readline  # [not win]
              - sqlite
              - curl
              - icu
              - oniguruma
            run:
              - openssl
              - libxml2
              - zlib
              - readline  # [not win]
              - sqlite
              - curl
              - icu
              - oniguruma
          
          test:
            commands:
              - php --version
          EOF

      - name: Build package
        uses: prefix-dev/rattler-build-action@v0.2.21
        with:
          recipe-path: recipe/recipe.yaml
          rattler-build-version: ${{ matrix.rattler-build-version }}
          artifact-name: php-${{ matrix.version }}-${{ matrix.os }}-${{ matrix.rattler-build-version }}
